/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    HiAffix: typeof import('hoci')['HiAffix']
    HiItem: typeof import('hoci')['HiItem']
    HiPopover: typeof import('hoci')['HiPopover']
    HiSelection: typeof import('hoci')['HiSelection']
  }
}
